### ISSUE TITLE
result can depend on order of numbers in list

### ISSUE THREAD

**Issue by gsullivan** [trinitum/perl-Number-Closest-XS#2]
The find_closest_numbers result can depend on the order of numbers in the list.

For example, if the number is 6, and the list contains 5 and 7, the result is 5.
But, if the list contains 7 and 5 in that order, the result is 7.

I added these lines to the closest.t test to demonstrate what I mean.

    eq_or_diff find_closest_numbers( 6, [ 5, 7 ] ), [5], "5 before 7";

    eq_or_diff find_closest_numbers( 6, [ 7, 5 ] ), [5], "7 before 5";

I submitted patches to eliminate this inconsistency for the similar pure
Perl Number::Closest* modules, but I don't know how to do the same for XS.
Refer to:

https://rt.cpan.org/Ticket/Display.html?id=106811

https://rt.cpan.org/Ticket/Display.html?id=106827

**Comment by trinitum** [comment]
Thank you for your report. There is actually no inconsistency, `find_closest_numbers($c, \@nums, $amount)` performs stable sort of items from `@nums` by the distance from `$c` and returns `$amount` of initial elements from the result. If you want some special order for elements that are equidistant from `$c`, you can presort `@nums` by desired criteria before passing it to `find_closest_numbers`. I should clarify that in module's documentation.
