### ISSUE TITLE
Loss of precision in least significant digit or two on Apple M1

### ISSUE THREAD

**Issue by tangentsoft** [trinitum/perl-Number-Closest-XS#3]
I get this test failure on a new ARM-based MacBook Pro:

```
t/closest.t .. 1/? 
    #   Failed test 'correct result with 64 bit integers'
    #   at t/closest.t line 63.
    # +----+------------------------+------------------------+
    # | Elt|Got                     |Expected                |
    # +----+------------------------+------------------------+
    # |   0|[                       |[                       |
    # *   1|  '37834034037159587',  |  '37834034037159585',  *
    # *   2|  '37834034037159585'   |  '37834034037159587'   *
    # |   3|]                       |]                       |
    # +----+------------------------+------------------------+

    #   Failed test 'correct result with 64 bit integers'
    #   at t/closest.t line 66.
    # +----+------------------------+------------------------+
    # | Elt|Got                     |Expected                |
    # +----+------------------------+------------------------+
    # |   0|[                       |[                       |
    # *   1|  '37834034037159587',  |  '37834034037159578',  *
    # *   2|  '37834034037159589'   |  '37834034037159585'   *
    # |   3|]                       |]                       |
    # +----+------------------------+------------------------+
```

This feels like roundoff error propagation.

The M1 is a 64-bit platform, but errors can still propagate.

Is this a real problem, or was I justified in installing it despite the test failure?

**Comment by trinitum** [comment]
Hi Warren. Please check the Caveats section in the module documentation https://metacpan.org/pod/Number::Closest::XS#CAVEATS. Internally it works by converting all the numbers into long double. If your perl hasn't been compiled with long double support, then it converts the numbers into double, which only has 52 bits precision and so you might not be getting correct results if you work with integers bigger than 2^52. Depending on your intended usage it might be acceptable or not. On my mac with Intel CPU perl has been compiled without long double support:
```
% perl -V | grep uselongdouble
    uselongdouble=undef
```

**Comment by tangentsoft** [comment]
That compilation default is the same with the stock Perl on my M1 mac, running Big Sur.

However, if this behavior of the Perl interpreter can be queried at test time, surely it should adapt the tests to test what's known to be expected on that platform? You wouldn't test COM APIs on Linux, and you wouldn't test `aio_*` networking APIs on Windows, so why test full 64-bit math on a system you can prove cannot support it?

It's fine to document this limitation in the manual, but to fail the tests? I don't see the justification.

You should do 52-bit tests on such platforms, that being the platform's limit.

Keep in mind that the tests are often run automatically by things like `sudo cpanm --installdeps .`, not by hand. There isn't sufficient justification to stall an automatic install pipeline here. The library does work, within a limited scope.

Also keep in mind that not all users of your library are using its full capability. I'm using your library only via `Math::Interpolate` on data that doesn't need anything even close to 52-bit precision.

**Comment by trinitum** [comment]
It's the question of priorities. For me correctness goes first. Your perl does support 64 bit integers and the module can't produce correct result given a set of 64 bit integers, hence the tests fail. Systems with 64 bit integers and without long double are not supported and I prefer getting reports about tests failing rather than about the module producing incorrect results (see #1). If you don't need such numbers you are free to install without tests passing, but it is for you to make the decision if the limitation is acceptable in your case and not for me.
